### ISSUE TITLE
bundler: command not found: puma

### ISSUE THREAD

**Issue by Brandl** [HoHoSoft/openproject-docker#5]
`openproject_1 | bundler: command not found: puma
openproject_1 | Install missing gem executables with `bundle install`

I get this error both when building branch "nginx-puma" and "openprojekt-5.0", though I'm mainly interested in the 5.0 branch.

Any ideas?

**Comment by Shevonar** [comment]
I assume you created a new container after the setup script has run in another container. The problem is that the setup script creates a `.setup-complete` file in the config volume and will not run again if such a file exists. In the new container the setup is not executed and puma will not be installed. Can you try to delete the `.setup-complete` file in the config folder and restart the container?
